-- Create keyword_current_summary_stage as a near-clone of
-- keyword_current_summary. Used by refreshKeywordCurrentSummary as the
-- write target during a refresh; once populated, it's atomically renamed
-- to swap into the live position.
--
-- Why: previously the refresh did TRUNCATE + INSERT inside a single
-- transaction, which meant the live keyword_current_summary held an
-- ACCESS EXCLUSIVE lock for the duration of the INSERT (~1-3 min). Any
-- explorer page load during that window would block until COMMIT. With
-- the stage-and-swap pattern, the live table is never locked beyond
-- the brief metadata-only RENAME at the very end.
--
-- LIKE INCLUDING ALL copies columns, defaults, NOT NULL/CHECK
-- constraints, and indexes (under autogenerated names). It does NOT
-- copy foreign keys, which is intentional — the bulk-load path doesn't
-- need FK validation cost; valid IDs come from the upstream kwm join
-- which already has its own FK to search_terms.
--
-- After each refresh, the stage and live tables swap names. The stage
-- table will hold the *previous* refresh's data until the next refresh
-- TRUNCATEs it. Index names rotate with the tables and don't get
-- renamed; expect EXPLAIN output to occasionally reference indexes
-- with names like "keyword_current_summary_stage_<col>_idx" against
-- the live keyword_current_summary table. Functional but visually
-- confusing — see refreshSummary.ts for the swap details.

CREATE TABLE IF NOT EXISTS "keyword_current_summary_stage"
  (LIKE "keyword_current_summary" INCLUDING ALL);
